import type { ParkingSpot } from '@/types/parking';

export const parkingSpots: ParkingSpot[] = [
  {
    id: '1',
    code: 'G_S5.2',
    type: 'open',
    propertyCode: 'G_D5.2',
    level: 'Ισόγειο',
    area: 13.2,
    price: 0,
    value: 0,
    valueWithSyndicate: 0,
    status: 'sold',
    owner: 'ΧΑΤΖΗΙΩΑΝΝΟΥ ΠΑΡΘΕΝΑ',
    floorPlan: '\\\\Server\\shared\\6. erga\\Palaiologou\\ΠΑΓΩΝΗΣ ΓΕΩΡΓΙΟΣ',
    constructedBy: 'ΠΑΓΩΝΗΣ ΓΕΩΡΓΙΟΣ',
    projectId: 1,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-15'
  },
  {
    id: '2',
    code: 'B_S5.7',
    type: 'open',
    propertyCode: 'B_D5.7',
    level: 'Ισόγειο',
    area: 12.5,
    price: 0,
    value: 0,
    valueWithSyndicate: 0,
    status: 'sold',
    owner: 'ΧΑΤΖΗΓΕΩΡΓΙΟΥ (Μ) ΚΑΘΑΡΙΝΑ ΔΗΜΗΤΡΑ',
    floorPlan: '\\\\Server\\shared\\6. erga\\Palaiologou\\ΠΑΓΩΝΗΣ ΓΕΩΡΓΙΟΣ',
    constructedBy: 'ΠΑΓΩΝΗΣ ΓΕΩΡΓΙΟΣ',
    projectId: 1,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-15'
  },
   {
    id: '3',
    code: 'A_P1.1',
    type: 'underground',
    propertyCode: 'A_D1.1',
    level: 'Υπόγειο 1',
    area: 11.5,
    price: 12000,
    value: 12000,
    valueWithSyndicate: 12500,
    status: 'available',
    owner: '',
    floorPlan: '',
    constructedBy: 'ΠΑΓΩΝΗΣ ΓΕΩΡΓΙΟΣ',
    projectId: 1,
    createdAt: '2024-01-01',
    updatedAt: '2024-02-01'
  },
  {
    id: '4',
    code: 'A_P2.2',
    type: 'underground',
    propertyCode: 'A_D2.2',
    level: 'Υπόγειο 1',
    area: 14.0,
    price: 15000,
    value: 15000,
    valueWithSyndicate: 15500,
    status: 'reserved',
    owner: 'Υποψήφιος Αγοραστής',
    floorPlan: '',
    constructedBy: 'ΠΑΓΩΝΗΣ ΓΕΩΡΓΙΟΣ',
    projectId: 1,
    createdAt: '2024-01-01',
    updatedAt: '2024-02-10'
  },
];
